<?php
/**
 * @file
 * Code for the Level Up Full View feature.
 */

include_once 'level_up_full_view.features.inc';

function level_up_full_view_entity_info_alter(&$entity_info) {
	$entity_info['node']['view modes']['level_up_full_view_display'] = array(
		'label' => t('Level Up : Full Display for Full View'),
		'custom settings' => TRUE,
	);
}


function level_up_full_view_preprocess_views_view(&$variables) {
  if (isset($variables['view']->name)) {
    $function = 'level_up_full_view_preprocess_views_view__'.$variables['view']->name; 
    if (function_exists($function)) {
     $function($variables);
    }
  }
}

function level_up_full_view_preprocess_views_view__levelup_subtopic_full(&$variables) {
  if($variables['display_id'] == 'page') {
    $nid = $variables['view']->result[0]->nid;
    $node = node_load($nid);
    $my_title = $node->title;

    $variables['view']->build_info['title'] = $my_title;
  }
}
